FROM node:12.13

WORKDIR /usr/src/backend

COPY ./dist ./dist

# Install dependencies
RUN apt update
RUN apt install -y nginx python3 python3-pip

# Create necessary dir for nginx (it throws an error otherwise)
RUN mkdir /run/nginx

ENV TYPEORM_ENTITIES=dist/**/*.entity.js,dist/src/**/*.entity.js
ENV TYPEORM_MIGRATIONS=dist/migration/*.js
ENV TYPEORM_MIGRATIONS_DIR=migration
ENV TYPEORM_SYNCHRONIZE=false

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install

EXPOSE 80 443
CMD sh -c "yarn start:prod & nginx -g 'daemon off;'"
